### PR TITLE
Update JupyterLab and mystjs extension

### PR DESCRIPTION
**Pull request by fperez**
Lab 3.6.1 adds RTC support - if the package update goes smoothly, we'll test the actual RTC functionality next.

The mystjs plugin fixes some pretty critical bugs.

### CODE REVIEW

**Review by ryanlovett — APPROVED** [review]
@balajialg This is a minor change in terms of configuration, but it will have major consequences as it will enable support for [real-time collaboration](https://jupyterlab.readthedocs.io/en/stable/user/rtc.html) between users. Excited to see how it turns out.

@fperez To turn on RTC I think it also needs an alteration to the jupyterhub-singleuser command. Did you just want to update lab for now or also enable RTC?

Previously the hub config specified:
```
  singleuser:
    cmd:
    - jupyterhub-singleuser
    - --LabApp.collaborative=true
```

The jupyterlab-links-share extension was also enabled. Should these be added as well? Previous related commits:
 - https://github.com/berkeley-dsep-infra/datahub/commit/93336ea1df0f02e139eaded7379f044ddf646533
 - https://github.com/berkeley-dsep-infra/datahub/commit/6b899a48cb776b46d7ef9de63ac44c6a313e6acb

**Comment by balajialg** [comment]
@ryanlovett Yes - super excited about this PR. If @fperez has a good time using RTC this semester then  folks who expressed interest to use RTC like [this](https://github.com/berkeley-dsep-infra/datahub/issues/3027#issuecomment-1324370838) will explore RTC next semester (or maybe even earlier)

**Comment by ryanlovett** [comment]
CI failed with
```
Encountered problems while solving.
Problem: package jupyterlab-3.6.1-pyhd8ed1ab_0 requires jupyterlab_server >=2.19,<3, but none of the providers can be installed
```
I've added jupyterlab_server as an explicit dependency (it is available in conda-forge), but I wonder if that will be sufficient to make mamba happy. Let's see.

**Comment by ryanlovett** [comment]
@fperez I tracked this down to a few conflicts. In a dev environment, besides jupyterlab needing jupyterlab_server==2.19.0, I found:

- jupyterlab_server needs jsonschema==4.17.3
- jsonschema needs altair==4.2.2, and jupyter-book to be removed

After those updates and removing jupyter-book, mamba was happy with the resulting environment. But I'm not sure how important jupyter-book is to your stack, so I haven't modified the PR further.

**Comment by ryanlovett** [comment]
Regarding jupyter-book, I think we just need https://github.com/executablebooks/jupyter-book/commit/48fb2faafc9dccb46c282f49059410dfd71fd07d so I resolved that by using jupyter-book master.

**Comment by fperez** [comment]
Thanks for tracking this down @ryanlovett! I pinged the JuptyerBook team to see how viable it would be for them to make a quick release so we can work off an official package rather than a git endpoint.

**Comment by fperez** [comment]
Note @ryanlovett that @choldgraf kindly made a [0.13.2](https://github.com/executablebooks/jupyter-book/releases/tag/v0.13.2) release just for us! We should be able to update to that from conda-forge shortly, which is wonderful.  Huge, huge ❤️ 🙏 to Chris!!

**Comment by ryanlovett** [comment]
Ah, even better. This has been merged to staging (so you can test there if you want) but I'll prep a new PR once the release is in conda-forge.

**Comment by choldgraf** [comment]
Just a note that if anybody on this team would be willing to help with Jupyter Book (and its underlying stack) maintenance, I am happy to give commit rights! Those projects are very under-resourced right now, and I won't be around in a few weeks to make releases just before bedtime (I'm expecting baby 2!)

**Comment by balajialg** [comment]
Hey @choldgraf Congratulations :) that's awesome news! Curious to know the kind of tasks you are expecting the maintainers to perform? I can help out in the interim but not sure whether I could do the technical wizardry that @ryanlovett exhibits.

**Pull request merged**
