### PR TITLE
Adding admin users for D-Lab hub as per the request from aculich via …

### PR DESCRIPTION
**Pull request by balajialg**
…email

### CODE REVIEW

**Review by felder — CHANGES_REQUESTED** [review]
I'm not versed enough with github to know if this merge will roll back the RAM changes.  Would you mind resubmitting the PR using the latest version of this file which does have those changes?

**Comment by yuvipanda** [comment]
@felder as i only see the admin names here, I don't think this will roll back the changes around RAM

**Comment by felder** [comment]
@yuvipanda ok.  @balajialg in which case I'll go ahead and merge it as is.

**Review by felder — APPROVED** [review]

**Comment by balajialg** [comment]
@yuvipanda @felder Apparently, these admin changes are not getting reflected in the DLab hub. Any idea why this is the case? https://github.com/berkeley-dsep-infra/datahub/issues/3463#issuecomment-1169377988

image

image

**Comment by felder** [comment]
@balajialg the changes do not appear to have made it to prod.

https://github.com/berkeley-dsep-infra/datahub/blob/prod/deployments/dlab/config/common.yaml

**Comment by felder** [comment]
@balajialg I just submitted a PR to merge this along with a bunch of other stuff to prod.

https://github.com/berkeley-dsep-infra/datahub/pull/3489

I've requested @ryanlovett and @yuvipanda to review those changes just to be sure they are ready.

**Pull request merged**
