### PR TITLE
removed older pinned versions of repo2docker, pin to latest release

### PR DESCRIPTION
**Pull request by shaneknapp**
@ryanlovett am i missing anything else?

### CODE REVIEW

**Comment by ryanlovett** [comment]
@shaneknapp I don't think repo2docker is actually needed inside the deployment images, just in requirements.txt. As far as I know, nobody is building images from within a hub. So my sense is rather than upgrade r2d within data100/data100-jl4, you can just remove it.

**Comment by shaneknapp** [comment]
+1 sgtm!

**Review by ryanlovett — APPROVED** [review]
Looks good! Give 2023.06.0 a try locally if you haven't already.

We can then release a new hubploy and bump that.

**Comment by shaneknapp** [comment]
> Looks good! Give 2023.06.0 a try locally if you haven't already.
> 
yep!  i built data100-jl4 in like 30sec and it worked like a charm.

> We can then release a new hubploy and bump that.

awesome

**Pull request merged**
