### PR TITLE
Add an apt.txt file with a few CLI tools that will be handy for Stat 159

### PR DESCRIPTION
**Pull request by fperez**
As suggested by @yuvipanda - I think these should do the trick, thx!

### CODE REVIEW

**Comment by fperez** [comment]
Huh?? I'm puzzled - for [the jupytearth image](https://github.com/pangeo-data/jupyter-earth/blob/c88a5bfab8bda1adf8373d12ab58e169aa56b75f/hub.jupytearth.org-image/Dockerfile#L31) we install `micro` just fine, but this build is [saying it can't find it](https://app.circleci.com/pipelines/github/berkeley-dsep-infra/datahub/989/workflows/4d5ae9d6-9a6d-4212-9f3f-8a35f320f4cd/jobs/8120?invite=true#step-108-974):

```
E: Unable to locate package micro
```

I'm not sure why, as it [supposedly works](https://github.com/zyedidia/micro/issues/583#issuecomment-687035485). Puzzled...

**Comment by yuvipanda** [comment]
@fperez oh that is strange. I think the packages need to be one per line. Can you try that?

Repo2Docker is also still using Ubuntu 18.04, maybe micro was added after that?

**Comment by fperez** [comment]
Ah, that's possible - I just put the packages one per line. But you're probably right about the 18.04 issue, as [per this comment](https://github.com/zyedidia/micro/issues/583#issuecomment-605624736).

**Comment by fperez** [comment]
[Here](https://snapcraft.io/install/micro/ubuntu) they suggest installing it as a snap:

```
sudo snap install micro --classic
```

Should that go into a postBuild file then?

**Comment by yuvipanda** [comment]
@fperez `postBuild` doesn't have admin, so we can't use that. 

For now, we can install it with conda from conda-forge: https://anaconda.org/conda-forge/micro. How does that sound?

**Comment by fperez** [comment]
And for now I'll just tell them to install it themselves :) 

```
curl https://getmic.ro | bash
```

**Comment by fperez** [comment]
Ah, cool, yes, even better!

**Comment by fperez** [comment]
I didn't realize conda-forge had it, thx!!

**Comment by fperez** [comment]
I'll update #3151 then to pull it in too.

**Pull request merged**
