### PR TITLE
Add allensdk package for MCB 160L class!

### LINKED ISSUE #3942: Install python package allensdk for class MCB-160L
### Package Name

allensdk

### Hub details

- Hub: Datahub
- Language: Python

### Course Name

https://classes.berkeley.edu/content/2022-fall-mcellbi-160l-001-lec-001

### Semester Details

Fall 2022

### Installation Deadline

Students will use this package as part of this class on Thursday and Friday this week. Recommended instructor to use !pip install till the package gets added to the image.

### PR DESCRIPTION
**Pull request by balajialg**
Fixes #3942!

### CODE REVIEW

**Comment by balajialg** [comment]
@shaneknapp @ryanlovett Need your help as @felder is on vacation today. I tried installing the Allen SDK package from conda forge - https://anaconda.org/conda-forge/allensdk. However, [Circle CI](https://app.circleci.com/pipelines/github/berkeley-dsep-infra/datahub/1809/workflows/de99a1bd-fd3d-4ed9-b4b7-1ac3fd060191/jobs/17287) throws the following error
 package pymatgen-2022.0.11-py37h2527ec5_0 requires numpy >=1.21.1,<2.0a0, but none of the providers can be installed.

Any idea what I might be missing?

**Comment by felder** [comment]
@balajialg I believe the issue is that the version of allensdk in conda forge is only for python 3.6

https://anaconda.org/conda-forge/allensdk/files

```
jovyan@jupyter-felder:~$ mamba install allensdk

                  __    __    __    __
                 /  \  /  \  /  \  /  \
                /    \/    \/    \/    \
███████████████/  /██/  /██/  /██/  /████████████████████████
              /  / \   / \   / \   / \  \____
             /  /   \_/   \_/   \_/   \    o \__,
            / _/                       \_____/  `
            |/
        ███╗   ███╗ █████╗ ███╗   ███╗██████╗  █████╗
        ████╗ ████║██╔══██╗████╗ ████║██╔══██╗██╔══██╗
        ██╔████╔██║███████║██╔████╔██║██████╔╝███████║
        ██║╚██╔╝██║██╔══██║██║╚██╔╝██║██╔══██╗██╔══██║
        ██║ ╚═╝ ██║██║  ██║██║ ╚═╝ ██║██████╔╝██║  ██║
        ╚═╝     ╚═╝╚═╝  ╚═╝╚═╝     ╚═╝╚═════╝ ╚═╝  ╚═╝

        mamba (0.16.0) supported by @QuantStack

        GitHub:  https://github.com/mamba-org/mamba
        Twitter: https://twitter.com/QuantStack

█████████████████████████████████████████████████████████████


Looking for: ['allensdk']

WARNING conda.lock:touch(51): Failed to create lock, do not run conda in parallel processes [errno 13]
conda-forge/noarch       [====================] (00m:03s) Done
conda-forge/linux-64     [====================] (00m:08s) Done

Pinned packages:
  - python 3.9.*


Encountered problems while solving:
  - package allensdk-0.14.4-py36h9f0ad1d_1 requires python >=3.6,<3.7.0a0, but none of the providers can be installed

jovyan@jupyter-felder:~$ mamba search -f allensdk

                  __    __    __    __
                 /  \  /  \  /  \  /  \
                /    \/    \/    \/    \
███████████████/  /██/  /██/  /██/  /████████████████████████
              /  / \   / \   / \   / \  \____
             /  /   \_/   \_/   \_/   \    o \__,
            / _/                       \_____/  `
            |/
        ███╗   ███╗ █████╗ ███╗   ███╗██████╗  █████╗
        ████╗ ████║██╔══██╗████╗ ████║██╔══██╗██╔══██╗
        ██╔████╔██║███████║██╔████╔██║██████╔╝███████║
        ██║╚██╔╝██║██╔══██║██║╚██╔╝██║██╔══██╗██╔══██║
        ██║ ╚═╝ ██║██║  ██║██║ ╚═╝ ██║██████╔╝██║  ██║
        ╚═╝     ╚═╝╚═╝  ╚═╝╚═╝     ╚═╝╚═════╝ ╚═╝  ╚═╝

        mamba (0.16.0) supported by @QuantStack

        GitHub:  https://github.com/mamba-org/mamba
        Twitter: https://twitter.com/QuantStack

█████████████████████████████████████████████████████████████

Loading channels: done
# Name                       Version           Build  Channel
allensdk                      0.14.4  py36h9f0ad1d_1  conda-forge
jovyan@jupyter-felder:~$
```

I think this would suggest we need to use pip to install it.

**Comment by felder** [comment]
@balajialg confirming the version of allensdk in conda forge (0.14.4) is quite old relative to the current in pypi:
https://pypi.org/project/allensdk/#history

**Comment by felder** [comment]
I'm going to close this PR and add allensdk 2.13.6 to requirements.txt (which instructs pip to install it) along with other changes I'm making.

**Comment by balajialg** [comment]
@felder Sounds good. I also created a commit based on your last comment but will ignore that. Thanks!

**Pull request closed without merging**
