### PR TITLE
[DH-301] some tooling to make syncing the user image dirs easier

### PR DESCRIPTION
**Pull request by shaneknapp**
@felder @ryanlovett @balajialg @gmerritt 

this should make cloning/syncing all of the user images a bit easier to manage.

i have all of my user images living in their own folder on my device(s), and got sick of manually running `for` loops on the CLI to sync/etc when performing ops on all of the images at once (like updating a workflow file across all images).

default help:

```
./manage-image-repos.py --help
usage: manage-image-repos.py [-h] [-c CONFIG] [-d DESTINATION] {sync,clone,branch,push} ...

positional arguments:
  {sync,clone,branch,push}
    sync                Sync all image repositories to the latest version.
    clone               Clone all image repositories.
    branch              Create a new feature branch in all image repositories.
    push                Push all image repositories to a remote.

options:
  -h, --help            show this help message and exit
  -c CONFIG, --config CONFIG
                        Path to file containing list of repositories to clone.
  -d DESTINATION, --destination DESTINATION
                        Location of the image repositories.
```

`sync` help:

```
./manage-image-repos.py sync --help
usage: manage-image-repos.py sync [-h] [-p] [-o ORIGIN]

options:
  -h, --help            show this help message and exit
  -p, --push            Push synced repo to a remote.
  -o ORIGIN, --origin ORIGIN
                        Origin to push to. This is optional and defaults to 'origin'.
```

`clone` help:

```
./manage-image-repos.py clone --help
usage: manage-image-repos.py clone [-h] [-s] [-g GITHUB_USER]

options:
  -h, --help            show this help message and exit
  -s, --set-origin      Set the origin of the cloned repository to the user's GitHub.
  -g GITHUB_USER, --github-user GITHUB_USER
                        GitHub user to set the origin to.
```

`branch` help:

```
./manage-image-repos.py branch --help
usage: manage-image-repos.py branch [-h] [-b BRANCH]

options:
  -h, --help            show this help message and exit
  -b BRANCH, --branch BRANCH
                        Name of the new feature branch to create.
```

`push` help:

```
./manage-image-repos.py push --help
usage: manage-image-repos.py push [-h] [-o ORIGIN] [-b BRANCH]

options:
  -h, --help            show this help message and exit
  -o ORIGIN, --origin ORIGIN
                        Origin to push to. This is optional and defaults to 'origin'.
  -b BRANCH, --branch BRANCH
                        Name of the branch to push.
```

usage examples below...

clone all of the image repos:

```
./manage-image-repos.py --destination ~/src/images/ --config repos.txt clone
```

clone all repos, and set `upstream` and `origin`:

```
./manage-image-repos.py --destination ~/src/images/ --config repos.txt clone --set-origin --github-user shaneknapp
```

how to sync all image repos from upstream and push to your `origin`:

```
./manage-image-repos.py --destination ~/src/images/ --config repos.txt sync --push
```

create a feature branch in all of the image repos:

```
./manage-image-repos.py -c repos.txt -d ~/src/images branch -b test-branch
```

after you've added/committed files, push everything to a remote:

```
./manage-image-repos.py -c repos.txt -d ~/src/images push -b test-branch
```

### CODE REVIEW

**Comment by shaneknapp** [comment]
hmm maybe instead of shelling out w/`subprocess` i could use [GitPython](https://gitpython.readthedocs.io/en/stable/)...

**Comment by shaneknapp** [comment]
@felder i know you use `https` when cloning/etc, but you should just be able to hack the config file pretty easily:

```
sed -i -e 's,:,/,g' repos.txt
sed -i -e 's,git@,https://,g' repos.txt
```

**Comment by ryanlovett** [comment]
@shaneknapp Cool! You mention `sync-image-repos.py` in this issue, which seems to be a previous name for the tool. It is not mentioned elsewhere, but just FYI in case you've got the above prepared in a readme somewhere.

This will also make updates easier when the workflows are reusable. You can use this to bump versions.

```yaml
call-reusable-workflow:
    uses: berkeley-dsep-infra/user-image-workflows/.github/workflows/something-something.yml@v2
    with:
      foo: 'bar'
```

**Comment by shaneknapp** [comment]
> @shaneknapp Cool! You mention `sync-image-repos.py` in this issue, which seems to be a previous name for the tool. It is not mentioned elsewhere, but just FYI in case you've got the above prepared in a readme somewhere.
> 
yah i changed the name mid-flight, and updated the first comment to correct the ones i missed.  :)

> This will also make updates easier when the workflows are reusable. You can use this to bump versions.
> 
> ```yaml
> call-reusable-workflow:
>     uses: berkeley-dsep-infra/user-image-workflows/.github/workflows/something-something.yml@v2
>     with:
>       foo: 'bar'
> ```

oooh, good idea!

**Comment by shaneknapp** [comment]
alright, gonna merge this now...

**Pull request merged**
