### PR TITLE
creating new data100 pool, plus adding Cesar to Data Retrieval Requests!

### PR DESCRIPTION
**Pull request by balajialg**
Cesar will support Jonathan with regard to Data retrieval requests!

### CODE REVIEW

**Comment by shaneknapp** [comment]
@balajialg did you push directly to staging, or use the github interface to make this change?  ;)

anyways, merging both yours and my changes to prod now.

**Comment by balajialg** [comment]
@shaneknapp I used the github interface to make this change and it allowed me to directly push to staging. Whenever I make changes to the github templates, I directly use the Github web app as it is a lot easier than creating a PR. Let me know if you have any reservations about this workflow.

**Comment by shaneknapp** [comment]
honestly, i'd much prefer that we use PRs for any changes outside of
documentation, etc.  when you push directly to staging this way, your
change was lumped in to mine and i only discovered it when i opened a PR to
merge my changes (https://github.com/berkeley-dsep-infra/datahub/pull/3892)
to prod.

the bigger issue is when you make code changes and directly push to staging
(see
https://github.com/berkeley-dsep-infra/datahub/commit/e3b660f460c08a028399943b23138b3ad98e8caa).
this actually skips all of the CI and build steps, and if this is broken
and someone were to try and push their own commit to prod, it'd actually
get deployed.

please use a new branch, PRs, etc.

shane

**Comment by shaneknapp** [comment]
ignore this, i see your response here:
https://github.com/berkeley-dsep-infra/datahub/commit/e3b660f460c08a028399943b23138b3ad98e8caa#commitcomment-88819692

;)

**Pull request merged**
