### PR TITLE
[DH-243] Adding geopandas and rtree packages to Datahub image to support LS 123 course

### LINKED ISSUE #5572: Request python package rtree for geopandas for Legal Studies 123
### Package Name

rtree (a dependency for making spatial joins in GeoPandas)

### Hub URL

datahub.berkeley.edu

### Course Name

Legal Studies 123 instructor Jonathan Marshall

### Semester Details

Spring 2024 (and spring semesters thereafter)

### Installation Deadline

Tuesday 27 February 2024
[13_PerformanceMetrics_solutions.pdf](https://github.com/berkeley-dsep-infra/datahub/files/14398548/13_PerformanceMetrics_solutions.pdf)

### PR DESCRIPTION
**Pull request by balajialg**
https://anaconda.org/conda-forge/rtree
https://anaconda.org/search?q=geopandas

Fixes #5572 and #5571

### CODE REVIEW

**Review by ryanlovett — CHANGES_REQUESTED** [review]
They're both packaged for conda so can be added to the top section.

Could you also please add Spring 2024 in the comment? If this is intended to be installed for every semester, that could be stated instead.

**Comment by balajialg** [comment]
Added required details to comment. 

> They're both packaged for conda so can be added to the top section.

@ryanlovett There are multiple packages (listing few below) that are conda specific and are listed at the bottom. Should this be scoped as a separate task?
```

  # Used by MCB32, but incompatible with ipywidgets 8.x
  # - qgrid==1.3.1

  # Engineering 7 https://github.com/berkeley-dsep-infra/datahub/issues/5337
  - otter-grader==4.4.1

  # Stat 165/265 requires prophet, Spring, 2024
  - prophet==1.1.5

  # https://github.com/berkeley-dsep-infra/datahub/issues/5497
  - ottr-force-save-labextension==0.1.1

  # [DH-231] Installing gh-scoped-creds for https://github.com/berkeley-dsep-infra/datahub/issues/5515
  - gh-scoped-creds==4.1
```

**Comment by ryanlovett** [comment]
@balajialg For this PR I was only referring to geopandas and rtree. The others, if done, should be a separate PR.

**Comment by balajialg** [comment]
So, I am building this image locally in my laptop to avoid burning circleci credits. Here is what I observed adding these packages to Datahub image,

- I added geopandas==0.14.3 and rtree==1.2.0 packages to the environment.yml file and built the image
- I was forced to upgrade pandas from version 1.3 to 1.4
- After that, I got the error message - "package linearmodels-5.4-py39h44dd56e_0 requires python >=3.9,<3.10.0a0, but none of the providers can be installed"
- For the sake of testing, I removed the version for geopandas and rtree packages and re-built the image, I got the following message - "package nodejs-16.4.1-h92b4a50_0 requires icu >=68.1,<69.0a0, but none of the providers can be installed"

**Comment by ryanlovett** [comment]
@balajialg What if you bump nodejs to 18 (as on dev-r) or to 20 (as on julia), or temporarily unspecify it? Iirc, sometimes the VS Code proxy doesn't like new versions of nodejs, but datahub doesn't have code-server.

**Comment by balajialg** [comment]
@ryanlovett Sharing the summary based on your suggestions below,

Case 1: When I try node.js version 18, I get the following error,
`package nodejs-18.10.0-h8839609_0 requires icu >=70.1,<71.0a0, but none of the providers can be installed
`
Case 2: When I try node.js version 20, I get the following error,
`  package pytensor-2.16.1-py311hb755f60_1 requires python >=3.11,<3.12.0a0, but none of the providers can be installed
`
Case 3: When I unversion node.js, I get the following error,
 `package fenics-2019.1.0-py39hf3d152e_30 requires fenics-dolfin 2019.1.0 py39h25c9216_30, but none of the providers can be installed
`
I am thinking of trying case 3. Thoughts?

**Comment by ryanlovett** [comment]
I would start with 3 as well. There is a 4th option which is to remove fenics since that was requested two years ago in #3305.

**Comment by balajialg** [comment]
Okay, removing fenics opens up a can of worms,

```
 - package spacy-3.4.1-py37h48bf904_0 requires python >=3.7,<3.8.0a0, but none of the providers can be installed
  - package cartopy-0.22.0-py39h5b8634a_0 requires python >=3.9,<3.10.0a0, but none of the providers can be installed
```

Removing spacy and cartopy results in 

```
Encountered problems while solving:
  - package python-3.9.18-1_73_pypy requires pypy3.9 7.3.15.*, but none of the providers can be installed
```
Unversioning spacy and cartopy results in

```
Encountered problems while solving:
  - package python-3.9.18-1_73_pypy requires pypy3.9 7.3.15.*, but none of the providers can be installed
  - package shapely-1.8.0-py37hc408c12_0 requires geos >=3.9.1,<3.9.2.0a0, but none of the providers can be installed
```

Unversioning shapely and adding a version of pypy3.9 results in

```
Encountered problems while solving:
  - package libxml2-2.11.5-h0d562d8_0 requires icu >=72.1,<73.0a0, but none of the providers can be installed
```

**Comment by balajialg** [comment]
Adding icu=72.* package to the image results in

```
Encountered problems while solving:
  - cannot install both icu-72.1-hcb278e6_0 and icu-70.1-h27087fc_0
  - package contextily-1.1.0-pyhd8ed1ab_0 requires rasterio, but none of the providers can be installed
```

Okay, this is getting out of hand atm

**Comment by balajialg** [comment]
@ryanlovett @shaneknapp - I got into a dependency hell with conda installation. I will just add this package via pip atm? I can't think of any alternatives that is simple than that.

**Comment by ryanlovett** [comment]
If pip works without trouble and conda doesn't, then I don't want to block you. Ideally conda would work and I hope that pip isn't upgrading or downgrading or otherwise messing with the versions we're telling it to. I also hope the libraries are still compatible, since conda is telling us that they're not. It'd be interesting to run a `mamba list` afterwards, and see if what is displayed matches what we're asking of conda+pip.

**Comment by balajialg** [comment]
Thanks @ryanlovett! Merging the changes to staging given the paucity of time at my end to debug this issue

`  - package graalpy-23.0.0-0_graalvm_native requires python_abi 3.10.* *_graalpy230_310_native, but none of the providers can be installed`

**Pull request merged**
