### PR TITLE
Add a shiny hub

### PR DESCRIPTION
**Pull request by yuvipanda**

### CODE REVIEW

**Comment by balajialg** [comment]
@yuvipanda Is the URL for this hub http://shiny.datahub.berkeley.edu/?

**Comment by ryanlovett** [comment]
@balajialg When it gets merged, yes.

**Comment by balajialg** [comment]
Thanks, @ryanlovett! @yuvipanda FYI - Prof plans to start the modules this week (he has classes today). So, it would be a good idea to merge this PR and test the hub at our end asap.

**Comment by jonathanferrari** [comment]
Any update on when this might be merged/when the server will be ready so I can get a nbgitpuller link to the professor? Thanks so much for all of your help on this by the way!

**Comment by ryanlovett** [comment]
The staging hub is up. @jonathanferrari are you able to test your course's apps at https://shiny-staging.datahub.berkeley.edu?

I tested [a polisci app](https://shiny-staging.datahub.berkeley.edu/hub/user-redirect/git-pull?repo=https%3A%2F%2Fgithub.com%2Fds-modules%2Fpolisci-3&branch=main&urlpath=shiny%2Fpolisci-3%2FModule_7_Hypothesis_Testing%2F) and it worked fine. Do _not_ send students to this hub as it is just for testing and may go away at any time.

**Comment by jonathanferrari** [comment]
Looks great! I loaded the notebooks and they seem to be working well! I'll wait for a non-testing version to send to the instructor.

**Comment by ryanlovett** [comment]
@jonathanferrari I think you may have logged into a different hub -- I don't see your login on shiny-staging yet.

**Comment by jonathanferrari** [comment]
weird, just tried it again through same link. did that work?

**Comment by ryanlovett** [comment]
Yep, I now see the login, thanks!

**Comment by ryanlovett** [comment]
shiny.datahub.berkeley.edu is now online, via #3870.

**Pull request merged**
