### PR TITLE
adding astro packages

### PR DESCRIPTION
**Pull request by profjsb**
Use Python 3.9.* to play nice with pytorch. Adding other data(science) tooling packages to the environment.yml. Use conda-forge for some of the complex packaging but pip for most.

### CODE REVIEW

**Comment by yuvipanda** [comment]
@profjsb you generally prefer pip over conda? Works ok with me, but just curious as I'm trying to reduce mixing of packages wherever possible.

**Comment by yuvipanda** [comment]
I've pushed a commit moving some of the config around to account for the fact that we're using a different authentication system here (chained via datahub.berkeley.edu rather than directly to bcourses). So everyone on the hub gets more RAM, rather than just students enrolled in a course.

**Comment by profjsb** [comment]
> @profjsb you generally prefer pip over conda? Works ok with me, but just curious as I'm trying to reduce mixing of packages wherever possible.

Few reasons: conda-forge packaging updates often lag pip in time (sometimes by many days). More important: the conflict resolution with conda-only packaging seems to take much longer than with pip, at least for this combination of packages we need.

**Comment by profjsb** [comment]
Thanks @yuvipanda -- I defer to your decisions around config changes. Please let me know when we're pushed to prod.

**Comment by yuvipanda** [comment]
@profjsb great! deployed now :)

**Pull request merged**
