### PR TITLE
[DH-189] Enable VSCode in Ischool Hub

### PR DESCRIPTION
**Pull request by balajialg**
JIRA ticket - https://jira-secure.berkeley.edu/browse/DH-189

Github Ref: https://github.com/berkeley-dsep-infra/datahub/issues/5251

Referred to Stat 159 hub PRs that enabled VSCode,

https://github.com/berkeley-dsep-infra/datahub/pull/4363
https://github.com/berkeley-dsep-infra/datahub/pull/4360

### CODE REVIEW

**Review by ryanlovett — APPROVED** [review]
Looks good to me!

I don't know if code-server still needs nodejs < 17. You could try setting nodejs to something like 18, and testing on staging. Or you can commit as-is and it will probably work.

**Comment by balajialg** [comment]
@ryanlovett just upgraded to nodejs version 18. Lets test it in staging

**Comment by balajialg** [comment]
@ryanlovett code-server still requires node-js <17. I am reverting nodejs to version 16 for now

**Comment by ryanlovett** [comment]
@balajialg Thanks for checking the nodejs dependency!

**Pull request merged**
