### PR TITLE
Update jupyterlab-myst to v 1.1.3

### PR DESCRIPTION
**Pull request by fperez**

### CODE REVIEW

**Comment by fperez** [comment]
cc @rowanc1

**Comment by rowanc1** [comment]
Excited for your feedback!!!

**Comment by fperez** [comment]
Looks solid on staging - @ryanlovett would it be possible to merge to prod? No rush though, at the next convenient time. Thx!!

**Comment by ryanlovett** [comment]
@fperez Merged and deployed!

**Pull request merged**
