### PR TITLE
Set up graphical desktop

### PR DESCRIPTION
**Pull request by fperez**
Add GUI tools and virtual desktop integration in JupyterLab.

### CODE REVIEW

**Comment by fperez** [comment]
Huge thanks @yuvipanda for the quick turnaround! Will test this extensively today and use it for lab and teaching next week. Will report back on results :)

**Comment by yuvipanda** [comment]
@fperez yw! https://github.com/berkeley-dsep-infra/datahub/pull/3212 will need to be merged before this is available in the stat159 hub. It's currently available in the stat159-staging.datahub.berkeley.edu hub tho

**Comment by fperez** [comment]
NP, thanks for the heads-up! All good, this isn't urgent :)

**Comment by fperez** [comment]
Awesome, just did a quick test on the staging hub, all 👍. 

🚀 !

**Comment by yuvipanda** [comment]
@fperez great. it's deployed now.

**Comment by balajialg** [comment]
@yuvipanda awesome stuff!

**Pull request merged**
