### PR TITLE
Adding an admin user for public health hub based on the issue #3168

### PR DESCRIPTION
**Pull request by balajialg**

### CODE REVIEW

**Review by felder — CHANGES_REQUESTED** [review]
github is complaining about conflicts.

Can you resolve those?
https://github.com/berkeley-dsep-infra/datahub/pull/3169/conflicts

**Comment by balajialg** [comment]
@felder Does the changes look good? Did I mess up something? If yes, I can create a new PR

**Comment by yuvipanda** [comment]
Looks good, @balajialg! Thanks for resolving the conflict!

**Comment by balajialg** [comment]
Thanks a lot @yuvipanda!

**Pull request merged**
