### PR TITLE
Increase memory allocation to 4GB for Data 100 student

### PR DESCRIPTION
**Pull request by balajialg**
As per @rohanjha123's request via Slack!

### CODE REVIEW

**Review by ryanlovett — APPROVED** [review]
Lgtm!

**Comment by rohanjha123** [comment]
Thanks sm for all your work! is there a way for me to know when this changes gets pushed from staging to prod? I can email the student as soon as it's in prod!

**Comment by shaneknapp** [comment]
> Thanks sm for all your work! is there a way for me to know when this changes gets pushed from staging to prod? I can email the student as soon as it's in prod!

it's in prod now!

**Comment by rohanjha123** [comment]
Thanks so much!

**Comment by balajialg** [comment]
Not sure whether this PR worked. Still shows that the allocated RAM is 2GB for this user :(
image

**Comment by ryanlovett** [comment]
@balajialg Ah, while the format you used was correct (based on the encrypted diff viewable at github.com), the username was not. It has "@berkeley.edu" appended.

**Comment by ryanlovett** [comment]
Prepared #4481.

**Comment by ryanlovett** [comment]
I did a manual hubploy so its on prod. The user will need to restart their server again.

**Comment by balajialg** [comment]
Ah, thanks a lot @ryanlovett for fixing that. I assumed it was the email id (Should have hubployed the changes sigh).  Your fix is working for the user.
image

**Pull request merged**
