### PR TITLE
Adding admins for Data 100 SU23 Datahub

### PR DESCRIPTION
**Pull request by mmiroyan**
Give Bennett Somerville and Mihran Miroyan Data 100 administrator permissions.

### CODE REVIEW

**Comment by ryanlovett** [comment]
@mihranmiroyan Are these two individuals part of course staff (instructors, tas, etc.), according to bcourses?

**Comment by mmiroyan** [comment]
Both Bennett and I are staff according to Bcourses (role: TA). 
We also need to add one of our instructors (Dominic) as admin on Data 100 Datahub (username: hangxingliu). His role is Teacher on Bcourses. I did not include his username in the PR, should I create another one?

**Comment by ryanlovett** [comment]
@mihranmiroyan If everyone you'd like to be a jupyterhub admin is an instructor or ta in the data100 bcourse course, then it would be sufficient to let us know the bcourse course ID. Then admin access will be granted automatically for all course staff.

Could you please go to https://github.com/berkeley-dsep-infra/datahub/issues/new/choose and get started on the "Admin Access Request" ? ([direct link](https://github.com/berkeley-dsep-infra/datahub/issues/new?assignees=balajialg&labels=support&projects=&template=admin_request.yml)) This helps us organize all such requests, even though you've created this issue already.

**Comment by mmiroyan** [comment]
@ryanlovett Just created a PR using the form and sent the usernames to ds-infrastructure@lists.berkeley.edu.
Thanks!

**Comment by ryanlovett** [comment]
Fixed by #4679.

**Pull request closed without merging**
