### PR TITLE
reduce replicas as its a small hub

### PR DESCRIPTION
**Pull request by shaneknapp**

### CODE REVIEW

**Review by ryanlovett — APPROVED** [review]
Lgtm!

**Comment by shaneknapp** [comment]
@ryanlovett what else do i need to do before/during/after merging this to prod?  kill the node placeholder pod?

**Comment by ryanlovett** [comment]
@shaneknapp You need to run `chartpress --push` in the same branch. This builds and pushes a new node-placeholder images, and alters the config to use that image. Similar to the info for building a new hub image.

**Comment by shaneknapp** [comment]
closing this as it'll be handled by https://github.com/berkeley-dsep-infra/datahub/pull/4340

**Pull request closed without merging**
