### PR TITLE
bump jupyterhub to 4.1.4

### PR DESCRIPTION
**Pull request by shaneknapp**
resolves https://github.com/berkeley-dsep-infra/datahub/security/dependabot/177

### CODE REVIEW

**Comment by ryanlovett** [comment]
@shaneknapp There are a bunch of later fixes related to xsrf after this one. You may want to wait a little bit.

**Comment by ryanlovett** [comment]
@shaneknapp See https://jupyterhub.readthedocs.io/en/stable/reference/changelog.html for more info about them.

**Comment by shaneknapp** [comment]
haven't seen any activity in the jupyterhub repo...  unless there's a new release in the next ~day i'll merge this to prod.

**Comment by ryanlovett** [comment]
Are you going to bump jupyterhub in the hub image as well?

**Comment by shaneknapp** [comment]
oh right, derp.  i do that in `datahub/images/hub/Dockerfile` yeah?

**Comment by ryanlovett** [comment]
Yes, if we're not going to bump z2jh itself. This also requires chartpressing.

When on staging, you might try exercising various proxied apps like rstudio and the desktop. That's where some of the xsrf-related issues were reported.

**Comment by shaneknapp** [comment]
hmm, probably best to update the z2jh version and do some testing on staging...

**Comment by shaneknapp** [comment]
i'll merge the PR this evening, and test out the proxied hubs in staging tomorrow morning.

**Pull request merged**
