### PR TITLE
Bump prometheus memory limit

### PR DESCRIPTION
**Pull request by yuvipanda**
We are getting some timeouts and memory usage seems very
near the limit

### CODE REVIEW

**Comment by yuvipanda** [comment]
Ah, if I look at `k get node <core-node-name> -o yaml` I see:

```
  allocatable:
    attachable-volumes-gce-pd: "127"
    cpu: 3920m
    ephemeral-storage: "47093746742"
    hugepages-1Gi: "0"
    hugepages-2Mi: "0"
    memory: 12667628Ki
    pods: "110"
```

So 16G is not allocatable on a single node.

**Comment by yuvipanda** [comment]
Ah, if I look at `k get node <core-node-name> -o yaml` I see:

```
  allocatable:
    attachable-volumes-gce-pd: "127"
    cpu: 3920m
    ephemeral-storage: "47093746742"
    hugepages-1Gi: "0"
    hugepages-2Mi: "0"
    memory: 12667628Ki
    pods: "110"
```

So 16G is not allocatable on a single node.

**Comment by felder** [comment]
core node pool node size increased in order to provide more RAM for this.  Issue #3311

**Comment by felder** [comment]
Confirmed:

```
kubectl get node gke-fall-2019-core-2022-03-24-21844ea2-41p0 -o yaml
...
  allocatable:
    attachable-volumes-gce-pd: "127"
    cpu: 7910m
    ephemeral-storage: "47093746742"
    hugepages-1Gi: "0"
    hugepages-2Mi: "0"
    memory: 27155364Ki
    pods: "110"
```

**Review by felder — COMMENTED** [review]
Looks good

**Pull request merged**
