### PR TITLE
Upgrading otter

### PR DESCRIPTION
**Pull request by rohanjha123**
This is a PR to upgrade otter-grader on the data 100 datahub to the newest version, which will introduce some nice functionality. I'm currently coordinating with the data 100 TAs on ensuring we can make the upgrade without any issues; just creating a pull request now for ease of communication.

### CODE REVIEW

**Comment by shaneknapp** [comment]
let me know if you'd like this merged to staging!

**Comment by rohanjha123** [comment]
Absolutely, thanks! For now we're still in the process of coordinating the package update, but I'll keep you updated when we're good to merge into staging

**Comment by rohanjha123** [comment]
We should be good to merge into staging! I'll be able to test it in staging sometime tomorrow afternoon/evening

**Comment by rohanjha123** [comment]
We should be good to push this to prod, thank you so much!!

**Comment by shaneknapp** [comment]
i'll merge this to prod tomorrow morning!

**Comment by rohanjha123** [comment]
thank youu!

**Pull request merged**
