### PR TITLE
Upgrading otter to a newer version

### PR DESCRIPTION
**Pull request by rohanjha123**
This PR involves upgrading otter to a newer version to make use of some awesome bug fixes. While this shouldn't be a breaking change, let's please wait for approval from the data 100 team (@CharlieJCJ @mihranmiroyan ) before merging this change

### CODE REVIEW

**Comment by rohanjha123** [comment]
could we rerun the checks? otter 5.2.3 just got released tonight: https://pypi.org/project/otter-grader/

**Comment by shaneknapp** [comment]
sounds good to me, let me know when i should merge to staging!

**Comment by rohanjha123** [comment]
We're ready to merge! Thank you sm!

**Comment by rohanjha123** [comment]
Thank you so much! Really appreciate it! How long will it take to be reflected in data100-staging.datahub.berkeley.edu? the staging is still on otter 5.1.3 right now

**Comment by shaneknapp** [comment]
> Thank you so much! Really appreciate it! How long will it take to be reflected in data100-staging.datahub.berkeley.edu? the staging is still on otter 5.1.3 right now

in about ~10 minutes or so.  the image is building and will be pushed out in a few minutes.

**Comment by shaneknapp** [comment]
alright, it's deployed to staging!

**Pull request merged**
