### PR TITLE
filestore testing do not merge me

### PR DESCRIPTION
**Pull request by felder**

### CODE REVIEW

**Comment by ryanlovett** [comment]
Things shared in the zoom chat:

- https://cloud.google.com/filestore/docs/creating-instances
- https://cloud.google.com/filestore/docs/creating-instances#configuring_ip-based_access_control
- https://cloud.google.com/filestore/docs/creating-instances#gcloud
- https://cloud.google.com/filestore/docs/creating-instances#instructions_for_creating_an_instance
- https://cloud.google.com/filestore/docs/editing-instances#gcloud
- https://cloud.google.com/filestore/docs/reference/rest/v1beta1/NfsExportOptions
- https://grafana.datahub.berkeley.edu/d/RzrUuuQZk/storage-i-o-statistics?orgId=1&refresh=5s
- `gcloud filestore instances describe testing-2022-12-13 --zone=us-central1-b --region=us-central1`
- `hub/templates/nfs-pvc.yaml`

**Comment by ryanlovett** [comment]
The command `gcloud filestore instances create --tier=BASIC_HDD testing-2-2022-12-13 --zone=us-central1-b --network=name="default" --flags-file=filestore-flags.json` failed, saying that there was no export option for Admin or some such. I think we might have to create a `read-write` + `no-root-squash` export option in the json file as documented [here](https://cloud.google.com/filestore/docs/creating-instances#configuring_ip-based_access_control).

Fyi, there's a tooltip in the cloud console when creating new instances. It says under Access control > Restrict access by IP address or range:
> Applies root squash to all clients, which maps root users to an anonymous user ID or group ID (defaulting to 65534).
You must assign an Admin so at least one user is excluded from root squash.

Screenshot 2022-12-13 at 4 17 45 PM

When using the console we chose the default of "Grant access to all client son the VPC network". However the CLI is forcing us to restrict access by IP, which is then forcing us to assign an Admin in the CLI, and we don't yet know how to do that.

**Comment by ryanlovett** [comment]
2i2c makes use of terraform and it documents filestore config at https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/filestore_instance.

**Comment by felder** [comment]
Thus far this is a multistep process:

1.  Create the instance in the web console
2. Mount the instance, cd to it, and `chown 1000:1000 .`
3. Update the instance settings to turn on root_squash
```
MacBook-Pro:config felder$ gcloud filestore instances update data100-2022-12-14 --zone=us-central1-b --flags-file=squash-flags.json
Waiting for [operation-1671061846826-5efd267c71cd4-9f594fe0-b7fac428] to finish...done.
MacBook-Pro:config felder$ cat squash-flags.json
 {
"--file-share":
  {
    "name": "shares",
    "capacity": "10TiB",
    "nfs-export-options": [
      {
        "access-mode": "READ_WRITE",
        "ip-ranges": ["10.0.0.0/8"],
        "squash-mode": "ROOT_SQUASH",
        "anon_uid": 1000,
        "anon_gid": 1000
      }
    ],
  }
}
```

**Comment by felder** [comment]
One thing to consider is seeing if we can have a separate nfs-export-options block to specify no_root_squash for our operations vm.

**Comment by shaneknapp** [comment]
filestores + modifications done for astro, biology, eecs, stat159

**Comment by ryanlovett** [comment]
Remember to do the following after configuring the deployment to use the filestore.
```
kubectl -n {hub}-{branch} delete pvc home-nfs-v3
kubectl -n {hub}-{branch} delete pvc home-nfs
```

**Comment by felder** [comment]
When you're ready to move a hub over (typically after a filestore instance is created for it and data is copied over) you need to modify each deployment thusly:

In deployments/HUB/config/common.yaml the nfs serverIP needs to be adjusted to match the IP of the corresponding filestore instance.   Also the pvcName needs to be home-nfs-v3.

Additionally deployments/HUB/config/staging|prod.yaml need to have their nfs sharenames adjusted.  Sharename should look something like shares/HUB/staging|prod

Lastly before you deploy you need to stop all the user pods and delete the persistent volume claims and the persistent volumes.

For example if you wanted to move astro-staging hub you might do the following:

First confirm the names of the stuff you're gonna delete:
```
MacBook-Pro:config felder$ kubectl -n astro-staging get pvc | grep nfs
home-nfs      Bound    astro-staging-home-nfs                     1Mi        RWX                           351d
home-nfs-v3   Bound    astro-staging-home-nfs-v3                  1Mi        RWX                           71d
MacBook-Pro:config felder$ kubectl get pv | grep astro-staging-home-nfs
astro-staging-home-nfs                     1Mi        RWX            Retain           Bound      astro-staging/home-nfs                                                     351d
astro-staging-home-nfs-v3                  1Mi        RWX            Retain           Bound      astro-staging/home-nfs-v3                                                  71d
```

Now delete them:
```
kubectl -n astro-staging delete pvc home-nfs
kubectl -n astro-staging delete pvc home-nfs-v3
kubectl delete pv astro-staging-home-nfs
kubectl delete pv astro-staging-home-nfs-v3
``` 

Helm should recreate them when you deploy.  If you don't do the above, helm will complain about the existence of those pvs and pvcs and the deployment will fail.

**Comment by felder** [comment]
```
disable hub pods to prevent logins
kubectl -n r-staging scale --replicas=0 deployment/hub
kubectl -n datahub-staging scale --replicas=0 deployment/hub
kubectl -n data100-staging scale --replicas=0 deployment/hub
kubectl -n biology-staging scale --replicas=0 deployment/hub
kubectl -n data8-staging scale --replicas=0 deployment/hub

kubectl -n r-prod scale --replicas=0 deployment/hub
kubectl -n datahub-prod scale --replicas=0 deployment/hub
kubectl -n data100-prod scale --replicas=0 deployment/hub
kubectl -n biology-prod scale --replicas=0 deployment/hub
kubectl -n data8-prod scale --replicas=0 deployment/hub

kill user pods
kubectl -n r-prod get pods | grep jupyter | cut -f1 -d ' ' | xargs -n1 -I {} kubectl -n r-prod delete pods {} --wait=false
kubectl -n datahub-prod get pods | grep jupyter | cut -f1 -d ' ' | xargs -n1 -I {} kubectl -n datahub-prod delete pods {} --wait=false
kubectl -n data8-prod get pods | grep jupyter | cut -f1 -d ' ' | xargs -n1 -I {} kubectl -n data8-prod delete pods {} --wait=false
kubectl -n data100-prod get pods | grep jupyter | cut -f1 -d ' ' | xargs -n1 -I {} kubectl -n data100-prod delete pods {} --wait=false
kubectl -n biology-prod get pods | grep jupyter | cut -f1 -d ' ' | xargs -n1 -I {} kubectl -n biology-prod delete pods {} --wait=false

kubectl -n r-staging get pods | grep jupyter | cut -f1 -d ' ' | xargs -n1 -I {} kubectl -n r-staging delete pods {} --wait=false
kubectl -n datahub-staging get pods | grep jupyter | cut -f1 -d ' ' | xargs -n1 -I {} kubectl -n datahub-staging delete pods {} --wait=false
kubectl -n data8-staging get pods | grep jupyter | cut -f1 -d ' ' | xargs -n1 -I {} kubectl -n data8-staging delete pods {} --wait=false
kubectl -n data100-staging get pods | grep jupyter | cut -f1 -d ' ' | xargs -n1 -I {} kubectl -n data100-staging delete pods {} --wait=false
kubectl -n biology-staging get pods | grep jupyter | cut -f1 -d ' ' | xargs -n1 -I {} kubectl -n biology-staging delete pods {} --wait=false

check running pods
kubectl -n datahub-staging get pods
kubectl -n r-staging get pods
kubectl -n data8-staging get pods
kubectl -n data100-staging get pods
kubectl -n biology-staging get pods

kubectl -n datahub-prod get pods
kubectl -n r-prod get pods
kubectl -n data8-prod get pods
kubectl -n data100-prod get pods
kubectl -n biology-prod get pods
```

**Comment by ryanlovett** [comment]
@felder Is this being done for all deployments or just those in the comment above?

**Comment by felder** [comment]
@ryanlovett all of them, eventually

**Comment by shaneknapp** [comment]
@felder we can probably close this...

**Comment by shaneknapp** [comment]
closing this PR!

**Pull request closed without merging**
