### PR TITLE
[DH-360] bumping placeholder values

### PR DESCRIPTION
**Pull request by shaneknapp**
https://jira-secure.berkeley.edu/browse/DH-360

@balajialg please review these values...  we might want to bump a couple of these hubs up past 1 but that will be on a hub-by-hub basis.

### CODE REVIEW

**Comment by balajialg** [comment]
@shaneknapp CE 70 (https://classes.berkeley.edu/content/2024-fall-civeng-70-001-lec-001) will be taught this semester and it will use CEE hub. We can either bump up the placeholder value for this hub or manage it with calendar events (around 100 students). Otherwise, Values look good to me.

**Comment by shaneknapp** [comment]
> @shaneknapp CE 70 (https://classes.berkeley.edu/content/2024-fall-civeng-70-001-lec-001) will be taught this semester and it will use CEE hub. We can either bump up the placeholder value for this hub or manage it with calendar events (around 100 students). Otherwise, Values look good to me.

i'll bump it to 1, and we can adjust this if we need to via calendar event(s).

**Comment by balajialg** [comment]
@shaneknapp sounds like a plan

**Comment by shaneknapp** [comment]
@balajialg btw, i wanted to point out that i set the `dev` hub to `0`...

**Comment by balajialg** [comment]
@shaneknapp thanks for the nudge! It should be good since discovery interns completed their work. I will add a calendar event whenever I need to access the dev hub.

**Pull request merged**
