### PR TITLE
Bump jupyter-server-proxy for security update.

### PR DESCRIPTION
**Pull request by ryanlovett**
https://github.com/jupyterhub/jupyter-server-proxy/security/advisories/GHSA-fvcq-4x64-hqxr

### CODE REVIEW

**Comment by shaneknapp** [comment]
thanks @ryanlovett !  we should talk about testing/deployment before any merging takes place.  :)

**Comment by ryanlovett** [comment]
@shaneknapp Sure, what did you have in mind?

**Comment by shaneknapp** [comment]
> @shaneknapp Sure, what did you have in mind?

as discussed in slack,  it's a proxy for other apps so i'd make sure everything works.  plus it's touching (almost) every hub.

links provided by @ryanlovett regarding the upstream changes:
https://github.com/jupyterhub/jupyter-server-proxy/commit/7abc9dc5bbb0b4b440548a5375261b8b8192fc22
https://github.com/jupyterhub/jupyter-server-proxy/commit/23dde350c2879525ca72aea5628a58f5d58d4483

**Comment by ryanlovett** [comment]
@shaneknapp +1. I've merged, and will post follow-up about testing hubs in this thread.

**Comment by ryanlovett** [comment]
Successfully tested

- [x] staging 
- [x] biology-staging
- [x] datahub-staging
- [x] eecs-staging
- [x] ischool-staging
- [x] publichealth-staging
- [x] r-staging
- [x] shiny-staging
- [x] stat20-staging

/rstudio, /desktop, and /vscode where available.

Used `git grep proxy= | grep -v -e syncthing -e server-proxy` from `deployments` to see what hubs are providing what apps.

**Comment by ryanlovett** [comment]
@shaneknapp I think this is good to merge to prod whenever.

**Pull request merged**
