### PR TITLE
adding a gitignore

### PR DESCRIPTION
**Pull request by shaneknapp**
coz i'm surprised we don't already have one!

### CODE REVIEW

**Comment by ryanlovett** [comment]
Looks good! Some others worth ignoring:
 - `docs/_build` - for those who test docs builds
 - `hub/charts` - for those who run chartpress

Regarding vi swap files, I put them in my own ~/.gitignore via `git config --global core.excludesfile ~/.gitignore`.

**Comment by shaneknapp** [comment]
> Regarding vi swap files, I put them in my own ~/.gitignore via `git config --global core.excludesfile ~/.gitignore`.

yeah, but not everyone does it that way...  doesn't really matter to me either way, so if you feel strongly about it i'll take it out!  ;)

**Comment by ryanlovett** [comment]
@shaneknapp No strong concerns about where to ignore vi swap files. We can ignore them in all the places. :)

**Comment by shaneknapp** [comment]
i have a feeling this file will be a regular WIP ;)

**Pull request merged**
