### PR TITLE
Uncomment Prob140 specific libraries in Datahub image

### PR DESCRIPTION
**Pull request by balajialg**
Not sure why these libraries got commented out as we haven't yet folded the Prob140 hub into Datahub!

### CODE REVIEW

**Review by shaneknapp — APPROVED** [review]

**Comment by shaneknapp** [comment]
> Not sure why these libraries got commented out as we haven't yet folded the Prob140 hub into Datahub!

yeah, this was my mistake to comment these out...  sorry about that!

**Comment by balajialg** [comment]
no worries at all @shaneknapp

**Review by shaneknapp — CHANGES_REQUESTED** [review]
remove the extra space before each `- <module name>`

**Comment by balajialg** [comment]
Ah, sorry about that! fixed it

**Review by shaneknapp — APPROVED** [review]

**Pull request merged**
