### PR TITLE
Bump cartopy version

### LINKED ISSUE #2824: Update Cartopy to version 0.20
### Package Name

cartopy

### Hub details

- Hub: D100
- Language: Python

### Course Name

Data 100 - me :)

### Semester Details

Fall 2021

### Additional Information

We already have cartopy, unfortunately there's a critical bug breaking our usage for an upcoming lecture that was [only very recently fixed  upstream](https://github.com/SciTools/cartopy/pull/1833/files). With 0.19, certain cartopy plot calls try to access that [old naciscdn.org](https://naciscdn.org) URL, which doesn't work at all anymore. The traceback is huge, here's just the relevant part:

```
/opt/conda/lib/python3.9/site-packages/cartopy/io/__init__.py in _urlopen(self=<cartopy.io.shapereader.NEShpDownloader object>, url='https://naciscdn.org/naturalearth/110m/physical/ne_110m_coastline.zip')
    240         """
    241         warnings.warn('Downloading: {}'.format(url), DownloadWarning)
--> 242         return urlopen(url)
        global urlopen = <function urlopen at 0x7f43280f8700>
        url = 'https://naciscdn.org/naturalearth/110m/physical/ne_110m_coastline.zip'
    243 
    244     @staticmethod

...
elided
...

URLError: <urlopen error [Errno -3] Temporary failure in name resolution>
```

Sorry for not having noticed this problem earlier!

### PR DESCRIPTION
**Pull request by yuvipanda**
Fixes https://github.com/berkeley-dsep-infra/datahub/issues/2824

### CODE REVIEW

**Comment by fperez** [comment]
Huge thanks @yuvipanda!!

**Comment by yuvipanda** [comment]
@fperez CI shows the same error you were getting earlier... I don't think this will be done today :( Might take a couple days to dig through this

**Comment by fperez** [comment]
Mmh, weird - @consideRatio [did the equivalent update](https://github.com/pangeo-data/jupyter-earth/issues/84) for the Jupytearth hub, and it went smoothly (I'm using it already). I'm curious what's different here - as far as I can tell, the bug is totally fixed in cartopy 0.20, so as long as that update goes in, we should be set.

**Comment by yuvipanda** [comment]
@fperez we use a mix of pip and apt, the pangeo image used by @consideRatio uses conda for everything

**Comment by fperez** [comment]
Ah, understood - thanks @yuvipanda for the clarification!

**Comment by yuvipanda** [comment]
@fperez what's your timeline on when this is required? Yesterday?

**Comment by fperez** [comment]
Not at all, no big rush - it's for early November! :)

**Comment by yuvipanda** [comment]
@fperez aaah, that is very good to know :)

**Comment by fperez** [comment]
Sorry for not mentioning that earlier, didn't mean to scare you!

Our guest lecture using these materials will be on Oct 28, actually - I thought it was November, sorry. But still, plenty of time! I can do all development locally so there's no rush, as long as it's there by Oct 28 in the morning US time.

Thanks so much!

**Comment by yuvipanda** [comment]
Verified this doesn't regress on https://github.com/berkeley-dsep-infra/datahub/issues/1796 by running the code snippet there

**Comment by yuvipanda** [comment]
This broke R packages that relied on `proj` tho, as suspected in a7af221ed0efbbce9b497fc0da33413ae34be35d.

**Pull request merged**
