### PR TITLE
Add psych and pacman packages to R hub image

### LINKED ISSUE #4203: Request R package "psych" and "pacman" for EEP/IAS C118
### Package Name

"psych" and "pacman"

### Hub details

- Hub: r.datahub and datahub
- Language: R

### Course Name

EEP 118
https://classes.berkeley.edu/content/2023-spring-envecon-c118-001-lec-001

IAS 118 (Crosslisted)
https://classes.berkeley.edu/content/2023-spring-ias-c118-001-lec-001

Sofia B Villas-Boas

### Semester Details

Spring 2023

### Installation Deadline

Sooner the better. We already started using one of the packages on 2/2/2023.

Thank you so much!!

### PR DESCRIPTION
**Pull request by balajialg**
fixes #4203!

Instructor needs these packages for using it in their classes next Tuesday! Have a meeting with them about this request later in the day today. Will update them about the importance of requesting these packages in advance!

### CODE REVIEW

**Comment by felder** [comment]
@balajialg this is not a huge deal and probably not worthy of another PR, but in the future please try to keep the spacing consistent in these files.

You can see that they are not consistent in the raw file output:
https://raw.githubusercontent.com/berkeley-dsep-infra/datahub/a36076635c7c4696027bccee6a9d4b737c3c4979/deployments/datahub/images/default/r-packages/eep-1118.r

This is often the result of using tabs instead of spaces.  Different editors use different values for the tab stops.  Some editors have a feature to convert tabs to spaces and what not and that can be useful to help avoid this.

**Comment by ryanlovett** [comment]
@felder That's a good point. For python I sometimes run `black` to automatically format code. You don't have to think about it -- it just makes fairly good choices. For R code, it looks like one can run something like:

```
R -e "formatR::tidy_file('eep-1118.r', width = 20, args.newline=TRUE)"
```

It somewhat adversely impacts our pairwise `class_libs` assignments regardless of what params are specified. (based on how it formats other files with more libraries, like orphaned-ph-142.r)

I also tried

```
R -e "styler::style_file('eep-1118.r', scope=I(c('tokens','spaces','indention')))"
```

which was a bit better IMO. The next time I touch one of the `.r` files I'll run it through [styler](https://styler.r-lib.org/articles/styler.html).

**Comment by balajialg** [comment]
Thanks @felder and @ryanlovett for your inputs! Fixed the tab spaces issue and will keep your inputs in mind

**Review by felder — APPROVED** [review]
Assuming this has no issues building due to dependencies or whatever, it looks good to me!

**Review by shaneknapp — APPROVED** [review]

**Pull request merged**
