### PR TITLE
Add retrolab package to the Data8 image

### PR DESCRIPTION
**Pull request by balajialg**
(Backup) In case the Data 8 instructional team decides to use the retro lab during SP 24!

### CODE REVIEW

**Comment by shaneknapp** [comment]
actually, do you need retrolab?  from their [github repo](https://github.com/jupyterlab/retrolab):

```
The RetroLab code base has now been integrated in the Jupyter Notebook GitHub repository: https://github.com/jupyter/notebook

Which means development is now happening in https://github.com/jupyter/notebook. Over the next weeks, we plan to triage the open issues in the RetroLab repository, and transfer them to the Notebook repo when relevant.
```

**Comment by balajialg** [comment]
@shaneknapp Good point! RetroLab is incompatible with Lab 4.0 and the build failed for that particular reason. 

```
The following packages are incompatible
├─ jupyterlab 4.0.10  is requested and can be installed;
└─ retrolab 0.3.21  is uninstallable because it requires
   └─ jupyterlab >=3.4.0,<4 , which conflicts with any installable versions previously reported.
```

However, we need retro because I tried launching a new retro notebook in the Data 8 Staging hub which has the latest NB7 and Lab 4 and it returned a 404 error. Specifying retro in nbgitpuller prepends "retro/tree" to the URL

https://data8-staging.datahub.berkeley.edu/hub/user-redirect/git-pull?repo=https%3A%2F%2Fgithub.com%2Fds-modules%2FLegalst-123&branch=master&urlpath=retro%2Ftree%2FLegalst-123%2Flabs%2F03_Numpy+to+Pandas+and+Dataframe+Operations%2F03_Numpy_to_Pandas_and_Dataframe_Operations.ipynb

**Comment by shaneknapp** [comment]
> However, we need retro because I tried launching a new retro notebook in the Data 8 Staging hub which has the latest NB7 and Lab 4 and it returned a 404 error. Specifying retro in nbgitpuller prepends "retro/tree" to the URL
> 
i'm not surprised that this is what's happening!  if retrolab isn't installed, then any links created via nbgitpuller that specify it will fail w/a 404.

basically, if retrolab is a requirement, we can't run jupyterlab 4.

is there a reason why we can't update the nbgitpuller links/docs/etc to reflect that retrolab is EOL?

**Comment by balajialg** [comment]
@shaneknapp Yes, we need to update the nbgitpuller docs to reflect that retro lab is EOL. Some upstream engagement is required to remove RetroLab from this list - https://nbgitpuller.readthedocs.io/en/latest/link.html

Do you know if Notebook 7 and Lab 3 are compatible? Data 8 hub requires Nb 7 but doesn't need Lab 4. If we downgrade to Lab 3, we can support retro at least till spring break. Instructors need to regenerate the links for the course website and point them to the nb7 interface. Retro could act as a backup interface till the transition is done.

**Comment by shaneknapp** [comment]
> @shaneknapp Yes, we need to update the nbgitpuller docs to reflect that retro lab is EOL. Some upstream engagement is required to remove RetroLab from this list - https://nbgitpuller.readthedocs.io/en/latest/link.html
> 
> Do you know if Notebook 7 and Lab 3 are compatible? Data 8 hub requires Nb 7 but doesn't need Lab 4. If we downgrade to Lab 3, we can support retro at least till spring break. Instructors need to regenerate the links for the course website and point them to the nb7 interface. Retro could act as a backup interface till the transition is done.

after confirming my suspicions locally w/repo2docker:  i don't think notebook 7 and jupyterlab < 4 will work together.

**Comment by ryanlovett** [comment]
The instructors will need to update their nbgitpuller links anyways for the new [materials-sp24](https://github.com/data-8/materials-sp24) repo, so switching the links from retro to notebook at the same time makes sense.

I wonder if we can add a redirect on the user server from /retro/tree (retro) to /tree (nb7). Few would notice since NB7 _is_ the new retro. This can be done with a jupyter-server-proxy config, but it may be possible to do in a jupyter config or helm chart config. But it'd be much easier to ditch retro and communicate the change.

**Comment by balajialg** [comment]
@ryanlovett I agree that switching to nb7 is the way forward. We might still need to support retro for a few weeks in case nb7 throws any new surprises for instructors. We encountered issues like this when we transitioned from classic to retro - https://github.com/berkeley-dsep-infra/datahub/issues/2992. nb7 has never been deployed in a course setting, unlike jl4 which was tested in Data 100 during SU 23.

A redirect for /retro/tree to /tree would be desirable but whether that is feasible given the tight timelines is a question I have.

**Comment by balajialg** [comment]
Closing this PR as we decided not to worry about retrolab for the Data 8 hub!

**Pull request closed without merging**
