### PR TITLE
[DH-51] initial commit of data100-jl4 hub

### PR DESCRIPTION
**Pull request by shaneknapp**
initial pass at data100/jupyterlab 4

### CODE REVIEW

**Comment by shaneknapp** [comment]
'they' are recommending replacing `jupyterlab-link-share` with `jupyter_collaboration`:
https://github.com/jupyterlab-contrib/jupyterlab-link-share/issues/59#issuecomment-1569690374
https://jupyterlab-realtime-collaboration.readthedocs.io/en/latest/

`ipywidgets` seems top be broken as well:
https://github.com/jupyter-widgets/ipywidgets/issues/3781
https://pypi.org/project/jupyterlab-widgets/

this was breaking but somehow unpinning the version made it work?
https://pypi.org/project/jupyter-bokeh/

**Comment by shaneknapp** [comment]
jupyterlab-drawio is broken as well...  ~~no issues for JL4 yet~~ i created an issue:
https://github.com/QuantStack/jupyterlab-drawio
https://github.com/QuantStack/jupyterlab-drawio/issues/119

**Comment by shaneknapp** [comment]
oof, `jupyterlab-git` doesn't work for JL 4.0:  https://github.com/jupyterlab/jupyterlab-git/issues/1245

**Review by felder — APPROVED** [review]
This looks reasonable to me.

**Pull request merged**
