### PR TITLE
Bump jupyter-syncthing-proxy version from 1.0.2 to 1.0.3

### PR DESCRIPTION
**Pull request by balajialg**

### CODE REVIEW

**Comment by balajialg** [comment]
Will close the pull request if the build runs into any issues!

**Comment by yuvipanda** [comment]
@balajialg this includes the changes you made for #3377 as well, can you separate it out?

**Comment by balajialg** [comment]
@yuvipanda Thanks for the nudge! Removed the storage policy-related document!

**Comment by yuvipanda** [comment]
@balajialg i still see the storage related changes unfortunately :(

**Comment by balajialg** [comment]
@yuvipanda I don't want to overcomplicate this but I am confused where the storage files are? Are you referring to this commit - https://github.com/berkeley-dsep-infra/datahub/pull/3381/commits/8594715ef16725447a88f243972576e199daa454?
I tried moving the HEAD back by a commit to see whether the staged changes had a storage policy file but I could not find any. Can you help me with this? 
image

or I can create a new pull request by closing this PR. Let me know the easiest way to fix this. Sorry for the trouble!

**Comment by yuvipanda** [comment]
@balajialg if I go to the 'files changed' in this PR, I see those changes - see https://github.com/berkeley-dsep-infra/datahub/pull/3381/files#diff-da2f7ad85c62d13d3e43eda89326da5bfb29a985d227f5b41054a651ca0fab16.

I can just fix this up if you'd like!

**Comment by balajialg** [comment]
@yuvipanda That will be really helpful. Appreciate it

**Comment by balajialg** [comment]
@yuvipanda I guess, I should give up on this and focus on other important stuff. Making novice git mistakes :(

**Comment by yuvipanda** [comment]
@balajialg fixed!

**Comment by balajialg** [comment]
@yuvipanda Thanks a ton! Appreciate it

**Pull request merged**
