### PR TITLE
Adding PR documentation to install R packages to resolve issue: #2608

### PR DESCRIPTION
**Pull request by balajialg**

### CODE REVIEW

**Review by felder — CHANGES_REQUESTED** [review]
These instructions for installing a package are more complicated than they likely need to be.

Like if the package in question is just missing, install.packages("packagename") is probably the best way to do an initial check to see if the default installation repo contains the package (and version) required.

Also I'm not sure "When testing RStudio with new version of the R package, add the following line to a cell at the beginning of your notebook." really applies here since the work occurs in RStudio typically and not in notebooks.

**Comment by balajialg** [comment]
@felder Removed the unnecessary changes based on your inputs. Let me know whether it suffices.

**Comment by balajialg** [comment]
@felder Any suggestions on the next step for this PR?

**Comment by felder** [comment]
@balajialg This is pretty good.  I don't think we should get much more complicated here such as using specific github commit ids (which is something we do) or some such.

**Pull request merged**
