### PR TITLE
[DH-301] adding workflow diagram

### PR DESCRIPTION
**Pull request by shaneknapp**

### CODE REVIEW

**Comment by ryanlovett** [comment]
@shaneknapp You may want to check out https://mermaid.js.org/syntax/flowchart.html. They can be integrated right into the doc so that if you want to make a change, you don't have go back to your drawing program, regenerate the SVG, etc. Here's an example of mermaid in a myst doc, https://jupyterhealth.org/software-documentation/security.

**Comment by ryanlovett** [comment]
Here are more in a jekyll README, https://github.com/berkeley-cdss/course-site-quarto.

**Comment by shaneknapp** [comment]
> Here are more in a jekyll README, https://github.com/berkeley-cdss/course-site-quarto.

this is *awesome*!  i'll do this now!  :)

**Comment by shaneknapp** [comment]
that's kinda amazing, tstl...

image

i'm curious as to why that one box w/the user's fork is a different color than the rest tho...

**Comment by ryanlovett** [comment]
> i'm curious as to why that one box w/the user's fork is a different color than the rest tho...

Good question! Sometimes I'll paste my mermaid diagram into the live editor at https://mermaid.live/ to see if it is a tooling issue, e.g. maybe the issue is due to quarto's mermaid integration.

**Comment by shaneknapp** [comment]
> > i'm curious as to why that one box w/the user's fork is a different color than the rest tho...
> 
> Good question! Sometimes I'll paste my mermaid diagram into the live editor at https://mermaid.live/ to see if it is a tooling issue, e.g. maybe the issue is due to quarto's mermaid integration.

it renders perfectly there...  i'll merge this and see what it looks like once it's live.

**Comment by shaneknapp** [comment]
> > > i'm curious as to why that one box w/the user's fork is a different color than the rest tho...
> > 
> > 
> > Good question! Sometimes I'll paste my mermaid diagram into the live editor at https://mermaid.live/ to see if it is a tooling issue, e.g. maybe the issue is due to quarto's mermaid integration.
> 
> it renders perfectly there... i'll merge this and see what it looks like once it's live.

boo it's still colored weirdly.

**Comment by ryanlovett** [comment]
I was about to say the same!

**Pull request merged**
