### PR TITLE
Spring 2022: Adding Data 100 instructors as admins as per issue #3198

### PR DESCRIPTION
**Pull request by balajialg**

### CODE REVIEW

**Review by felder — CHANGES_REQUESTED** [review]
Please resolve the indicated merge conflicts.

Also, doesn't #3198 mention hug@cs.berkeley.edu?  I'm not sure if that'll work since authentication eventually ends up being by calnet id.

@ryanlovett @yuvipanda Do you know?  Will the username portion of @cs.berkeley.edu addresses work for adding admin access as requested in #3198 ?

**Comment by balajialg** [comment]
@felder Resolved the merge conflict! Requested the TA for instructor's berkeley.edu email id. Prior conversations related to this issue can be seen [here](https://github.com/berkeley-dsep-infra/datahub/pull/2649) which highlights that this shouldn't be a problem. Let me know if you think otherwise

**Comment by felder** [comment]
@balajialg I was looking for that!  I vaguely recalled this coming up before.

I did look to see if I could find them in the user list (as a non admin) but I could not.  Note that in the conversation you linked, it could be that particular user happened to use the same name for both their calnet ID and the cs.berkeley.edu address.

I guess if they find they don't have admin rights, we can ask them to check what the system says their name is as yuvi suggested.

**Comment by balajialg** [comment]
@felder Makes sense!

**Pull request merged**
