### PR TITLE
add labels for  LICENSE, github issue template, helm/chart , and support and hub deployment changes

### PR DESCRIPTION
**Pull request by shaneknapp**
i missed these two dirs in our repos and they should most certainly have their own labels!

@ryanlovett @felder any thoughts on the naming of these labels?

### CODE REVIEW

**Comment by shaneknapp** [comment]
once we agree on label names, i'll use this PR as an opportunity to normalize to single quotes instead of a mix of those and double.

**Comment by ryanlovett** [comment]
Do you want to label all chart-related matters? e.g. chartpress.yaml, Chart.yml, values.yaml, etc. This would intersect with some of the others but could be useful for search.

`documentation` doesn't catch README.md or LICENSE at the top level, although they're probably not going to change.

**Comment by shaneknapp** [comment]
> Do you want to label all chart-related matters? e.g. chartpress.yaml, Chart.yml, values.yaml, etc. This would intersect with some of the others but could be useful for search.
> 
yes, great idea.

> `documentation` doesn't catch README.md or LICENSE at the top level, although they're probably not going to change.

actually it does!  `**/*.md` globs for any `md` files at any level of the repo hierarchy.  :)

**Comment by ryanlovett** [comment]
> actually it does! **/*.md globs for any md files at any level of the repo hierarchy. :)

Ahh, TIL! When then just LICENSE, but that's not critical.

**Comment by shaneknapp** [comment]
> > actually it does! **/*.md globs for any md files at any level of the repo hierarchy. :)
> 
> Ahh, TIL! When then just LICENSE, but that's not critical.

not critical, but quite easy...  :)

**Pull request merged**
