### PR TITLE
Increase memory requirement to 4 GB for Data 200 students 

### PR DESCRIPTION
**Pull request by balajialg**

### CODE REVIEW

**Comment by balajialg** [comment]
Fixes #4472

**Review by ryanlovett — COMMENTED** [review]
That is the correct syntax. Does it need an altered ramp up and end date like in #4472?

**Comment by balajialg** [comment]
@ryanlovett yes - I will update the config and add a new commit in this PR soon

**Comment by balajialg** [comment]
@shaneknapp Increased the RAM to 4GB as per the instructors request [here](https://github.com/berkeley-dsep-infra/datahub/issues/4472#issuecomment-1506162111). Can you merge this to staging?

**Review by shaneknapp — APPROVED** [review]

**Pull request merged**
