### PR TITLE
Moving dependencies to conda-forge for julia, issue #2934

### PR DESCRIPTION
**Pull request by felder**

### CODE REVIEW

**Comment by felder** [comment]
@yuvipanda I didn't move matplotlib from requirements.txt, but I can (or at least I'll check to see if I can).

As I'm sure you could imagine, there were some packages that I could not find in conda-forge.

What I opted to do was to list them in environment.yml, but commented out.  I also did the reverse infra-requirements.txt, that is I commented out the ones I moved and didn't comment out the ones I couldn't.

If this generally looks good, let me know and I'll proceed with a similar methodology for the rest of the hubs.  If there's other stuff related to this task you think I should also do, also please let me know!

**Comment by yuvipanda** [comment]
This is a great start, @felder! 

Since the infra-requirements.txt package is common across all images, let's actually tackle that *last* - it's still useful to bump some packages across the images (like with https://github.com/berkeley-dsep-infra/datahub/pull/2969). Instead, just move what's in requirements.txt to environment.yml?

**Comment by felder** [comment]
@yuvipanda I'm a bit confused here, because in #2934 you commented with "Move infra-requirements.txt to install from conda, by specifying it in environment.yml"

What did you mean by this?

**Comment by yuvipanda** [comment]
@felder ah, so the question is one of order of operations. infra-requirements.txt does need to be moved, but the canonical copy is in https://github.com/berkeley-dsep-infra/datahub/blob/staging/scripts/infra-packages/requirements.txt and https://github.com/berkeley-dsep-infra/datahub/blob/staging/scripts/infra-packages/sync.bash is the script that ensures that they are the same across the images. So if we were to move infra-packages, we'll have to move *that* requirements.txt to an environment.yml file, and write a somewhat more complex script to keep that in sync across the images, as I'm guessing it might not be in multiple environment.yml files. Hence my suggestion here that we move https://github.com/berkeley-dsep-infra/datahub/blob/staging/deployments/julia/image/requirements.txt as that's just specific to the julia image.

**Comment by felder** [comment]
@yuvipanda ok got it.

I'll close this PR and submit another with just requirements.txt moved.

Is this general case for all the rest of the images as well?

**Comment by yuvipanda** [comment]
@felder yeah, I think that's the way to go. We can do infra-requirements.txt last?

**Comment by felder** [comment]
@yuvipanda sure.  I'll set the files aside so that when it is time to approach that, I'll already know which items are in conda forge.

**Pull request closed without merging**
