### PR TITLE
Update infer and stat20data

### PR DESCRIPTION
**Pull request by andrewpbray**

### CODE REVIEW

**Comment by felder** [comment]
I'm going to close this pull request for now.  If it turns out we can update this package without causing issues for ph142, we will submit another PR to do so.

**Comment by andrewpbray** [comment]
Is it ok to reopen this one now since it sounds like PH is not on r.datahub?

**Comment by felder** [comment]
@andrewpbray the fix for infer is still being deployed.

**Comment by ryanlovett** [comment]
@andrewpbray I'm pulling in stat20data update via #2885. infer is now in staging at 1.0.0 via your original specification in stat-20.r and with ph-1.4.2's infer removed.

**Pull request closed without merging**
